### ISSUE TITLE
还是会出现框

### ISSUE THREAD

**Issue by lingchuanbo** [BetterWorld-Liuser/XiaoChao#10]
![QQ截图20220305100142](https://user-images.githubusercontent.com/4213515/156863476-800a6e89-dcbf-45c0-948e-a17497c177f1.png)
1.更新到这个版本会有虚线框 上一个版本不会
2.关于+号 显示为空 建议用配置模式（因为我觉得显示更好看✍🏻️）

**Comment by BetterWorld-Liuser** [comment]
好的，不过需要等一段时间。

**Comment by BetterWorld-Liuser** [comment]
发一个beta版吧，不会有虚线框
