### ISSUE TITLE
有"+"号看的更清楚明白一些，希望能改回以前的样子

### ISSUE THREAD

**Issue by uulaile** [BetterWorld-Liuser/XiaoChao#11]
![image](https://user-images.githubusercontent.com/96331996/157370967-cb023206-e50f-440b-bcf1-696230037790.png)

**Comment by BetterWorld-Liuser** [comment]
好的

**Comment by BetterWorld-Liuser** [comment]
![image](https://user-images.githubusercontent.com/37199800/157609996-2f59f862-ef5a-4080-8ac9-c046fab71056.png)
最新beta版的样子，还满意吗？
