### ISSUE TITLE
能不能3列4列自己调整，3列能显示的文字可以多些

### ISSUE THREAD

**Issue by uulaile** [BetterWorld-Liuser/XiaoChao#14]
![image](https://user-images.githubusercontent.com/96331996/157809245-086efd85-88c6-4acc-8738-6193ea1dcd99.png)

**Comment by BetterWorld-Liuser** [comment]
可以

**Comment by BetterWorld-Liuser** [comment]
三列调整完毕
![image](https://user-images.githubusercontent.com/37199800/158042261-8d1d3c3e-4d4b-4ee2-a46a-a9df5d125be6.png)

**Comment by uulaile** [comment]
老师，很强大，可以去吾爱破解论坛发一下。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BetterWorld-Liuser/XiaoChao"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月13日(星期天) 上午10:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BetterWorld-Liuser/XiaoChao] 能不能3列4列自己调整，3列能显示的文字可以多些 (Issue #14)





 
三列调整完毕
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by BetterWorld-Liuser** [comment]
帮我多宣传宣传，谢谢～@uulaile

**Comment by uulaile** [comment]
那我代你发一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BetterWorld-Liuser/XiaoChao"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月13日(星期天) 上午10:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BetterWorld-Liuser/XiaoChao] 能不能3列4列自己调整，3列能显示的文字可以多些 (Issue #14)





 
***@***.***
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by uulaile** [comment]
https://www.52pojie.cn/thread-1601979-1-1.html
我发了一个，你看看有没有问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BetterWorld-Liuser/XiaoChao"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月13日(星期天) 上午10:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BetterWorld-Liuser/XiaoChao] 能不能3列4列自己调整，3列能显示的文字可以多些 (Issue #14)





 
***@***.***
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by BetterWorld-Liuser** [comment]
emmm，你的帖子可能会被删，我在吾爱上以前发过一帖，后来管理员说不能发新的了...



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月13日(周日) 中午11:54
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [BetterWorld-Liuser/XiaoChao] 能不能3列4列自己调整，3列能显示的文字可以多些 (Issue #14)




 https://www.52pojie.cn/thread-1601979-1-1.html 
 我发了一个，你看看有没有问题。 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "BetterWorld-Liuser/XiaoChao"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年3月13日(星期天) 上午10:43 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [BetterWorld-Liuser/XiaoChao] 能不能3列4列自己调整，3列能显示的文字可以多些 (Issue #14) 
 
 
 
 
 
   
 ***@***.*** 
   
 — 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by uulaile** [comment]
看看吧，现在审核中




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BetterWorld-Liuser/XiaoChao"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月13日(星期天) 中午11:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BetterWorld-Liuser/XiaoChao] 能不能3列4列自己调整，3列能显示的文字可以多些 (Issue #14)





 emmm，你的帖子可能会被删，我在吾爱上以前发过一帖，后来管理员说不能发新的了... 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2022年3月13日(周日) 中午11:54 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;;"State ***@***.***&amp;gt;; 
 主题: Re: [BetterWorld-Liuser/XiaoChao] 能不能3列4列自己调整，3列能显示的文字可以多些 (Issue #14) 
 
 
 
 
  https://www.52pojie.cn/thread-1601979-1-1.html  
  我发了一个，你看看有没有问题。  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "BetterWorld-Liuser/XiaoChao"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2022年3月13日(星期天) 上午10:43  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [BetterWorld-Liuser/XiaoChao] 能不能3列4列自己调整，3列能显示的文字可以多些 (Issue #14)  
   
   
   
   
   
     
  ***@***.***  
     
  —  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.   
  You are receiving this because you were mentioned.Message ID: ***@***.***&amp;amp;gt;  
 — 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 You are receiving this because you modified the open/close state.Message ID: ***@***.***&amp;gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shroro** [comment]
快捷键内容多的话，会整个挪到右边，变成只有右边一列，无法显示3列

**Comment by Crunchbits** [comment]
Any update on if this is possible yet, and if so how?

**Comment by BetterWorld-Liuser** [comment]
@Crunchbits Sorry in fact, i have little time to maintain this project.
