### ISSUE TITLE
打开文件有BUG

### ISSUE THREAD

**Issue by uulaile** [BetterWorld-Liuser/XiaoChao#17]
![image](https://user-images.githubusercontent.com/96331996/159107426-a05a1458-0fb6-43e1-af56-fca7c998ee04.png)

**Comment by BetterWorld-Liuser** [comment]
你是干测试的吗？？？？
了解了，下版本修复....

**Comment by uulaile** [comment]
😂

**Comment by BetterWorld-Liuser** [comment]
顺便说一下，如果你把测试版的文件全部覆盖进去，你的原始文件可能会有损失，所以覆盖的时候注意一下。

**Comment by uulaile** [comment]
发现了，如果新版本全部文件覆盖进去老版本，"设置"这个会打不开。

**Comment by BetterWorld-Liuser** [comment]
新版本是附带我自己的设置文件的，一般来说设置.md、data、local文件夹不需要复制。

**Comment by BetterWorld-Liuser** [comment]
我考虑了做个安装包或者其他什么的，但是目前打包感觉体验很不好，很烦。

**Comment by uulaile** [comment]
千万别安装包形式。只要"写一个使用必读"就好了 
https://meta.appinn.net/t/topic/30894  这个刚出的类似的，那些收藏夹形式可以考虑一下，创意非常好，快捷键太多，要找半天，有个收藏夹功能，能更快找到不熟悉的，熟悉了以后，又可以去掉收藏。

**Comment by uulaile** [comment]
快捷键 ctrl+ctrl ，这样双击形式打开的能搞吗？

**Comment by BetterWorld-Liuser** [comment]
这个软件我这几天也看了，也不错的。收藏功能暂时不考虑开发，你可以尝试在原本添加路径的地方随便写一个字符，这样它就会显示在最后一列了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月19日(周六) 中午1:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [BetterWorld-Liuser/XiaoChao] 打开文件有BUG (Issue #17)




 
千万别安装包形式。只要"写一个使用必读"就好了
 https://meta.appinn.net/t/topic/30894  这个刚出的类似的，那些收藏夹形式可以考虑一下，创意非常好，快捷键太多，要找半天，有个收藏夹功能，能更快找到不熟悉的，熟悉了以后，又可以去掉收藏。

**Comment by BetterWorld-Liuser** [comment]
可以搞（加到计划表最后一位



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月19日(周六) 中午1:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [BetterWorld-Liuser/XiaoChao] 打开文件有BUG (Issue #17)




 
快捷键 ctrl+ctrl ，这样双击形式打开的能搞吗？

**Comment by uulaile** [comment]
![image](https://user-images.githubusercontent.com/96331996/159108255-4936fa33-7ca5-4df9-99be-13a5a98df490.png)

**Comment by BetterWorld-Liuser** [comment]
对于收藏的这件事，第一个回答。
对于ctrl➕ctrl快捷键这事，第二个回答。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月19日(周六) 中午1:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [BetterWorld-Liuser/XiaoChao] 打开文件有BUG (Issue #17)

**Comment by uulaile** [comment]
我的意思是怎么去操作

**Comment by BetterWorld-Liuser** [comment]
在一般的数据，比如ctrl+c 复制 这一行后面加一个空格，然后继续写任意字符



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月19日(周六) 中午1:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [BetterWorld-Liuser/XiaoChao] 打开文件有BUG (Issue #17)




 
我的意思是怎么去操作

**Comment by uulaile** [comment]
想想，那个收藏夹不要也没事，全部快捷键都显示出来也没什么用，自己有用的添加上去就好了🤣

**Comment by BetterWorld-Liuser** [comment]
就是呀，本来快捷键就是自己加的，看烦了自己删掉就行了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月19日(周六) 下午2:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [BetterWorld-Liuser/XiaoChao] 打开文件有BUG (Issue #17)




 
想想，那个收藏夹不要也没事，全部快捷键都显示出来也没什么用，自己有用的添加上去就好了🤣

**Comment by uulaile** [comment]
那CTRL+ CTRL，这个怎么弄？

**Comment by BetterWorld-Liuser** [comment]
不是说了嘛，加到代办列表最后一位了哈哈哈



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月19日(周六) 下午2:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [BetterWorld-Liuser/XiaoChao] 打开文件有BUG (Issue #17)




 
那CTRL+ CTRL，这个怎么弄？

**Comment by uulaile** [comment]
![image](https://user-images.githubusercontent.com/96331996/159110680-76e4a060-d557-4e77-85d0-48476502a3cd.png)
这样搞不起来，代办列表在哪里找不到😂，麻烦老师了

**Comment by BetterWorld-Liuser** [comment]
我自己的代办列表，捐赠可以让它提速（疯狂暗示



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月19日(周六) 下午2:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [BetterWorld-Liuser/XiaoChao] 打开文件有BUG (Issue #17)




 

 这样搞不起来，代办列表在哪里找不到😂，麻烦老师了

**Comment by BetterWorld-Liuser** [comment]
好家伙，真给了ｸﾞｯ!(๑•̀ㅂ•́)و✧，下个版本就出。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月19日(周六) 下午2:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [BetterWorld-Liuser/XiaoChao] 打开文件有BUG (Issue #17)




 

 这样搞不起来，代办列表在哪里找不到😂，麻烦老师了

**Comment by uulaile** [comment]
捐赠完毕，(疯狂暗示

**Comment by uulaile** [comment]
￥$，这样暗示明显一点😂

**Comment by uulaile** [comment]
笑死我了

**Comment by uulaile** [comment]
![image](https://user-images.githubusercontent.com/96331996/159111020-3ed009fc-b330-4811-b7d3-792351d803c3.png)
贴这个更好，更明显

**Comment by BetterWorld-Liuser** [comment]
下次把里面标题标记 # 换成￥

**Comment by uulaile** [comment]
Win+; 表情符号
这个我才发现有这个功能，以前不知道。

**Comment by BetterWorld-Liuser** [comment]
之后准备放一系列的预置快捷键，但是我没太多空，如果你愿意加入contributor的话可以pull request(ฅ•﹏•ฅ)



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月19日(周六) 下午3:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [BetterWorld-Liuser/XiaoChao] 打开文件有BUG (Issue #17)




 
Win+; 表情符号
 这个我才发现有这个功能，以前不知道。

**Comment by uulaile** [comment]
想是想，不会开发写代码，遗憾，还是计算机系的，没好好读书

**Comment by uulaile** [comment]
![image](https://user-images.githubusercontent.com/96331996/159111538-3cfe4c8b-1939-4d48-81b2-5307a801a8f7.png)
这个怎么弄

**Comment by BetterWorld-Liuser** [comment]
因为你合并了我的数据，新上传的软件包是我直接把我的软件打包上传，你去全局.md删掉那行的链接就行。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月19日(周六) 下午3:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [BetterWorld-Liuser/XiaoChao] 打开文件有BUG (Issue #17)




 

 这个怎么弄

**Comment by uulaile** [comment]
点"确定"obsidian还是能打开的，无所谓的

**Comment by BetterWorld-Liuser** [comment]
OK



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月19日(周六) 下午3:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [BetterWorld-Liuser/XiaoChao] 打开文件有BUG (Issue #17)




 
点"确定"obsidian还是能打开的，无所谓的

**Comment by BetterWorld-Liuser** [comment]
已修复，查看22.2.1-beta6版本
