### ISSUE TITLE
在双显示器未正常运行

### ISSUE THREAD

**Issue by lingchuanbo** [BetterWorld-Liuser/XiaoChao#2]
1.在双显示器未正常运行，始终在一个窗口显示，理想状态是显示器A按快捷键就在显示器A显示，显示器B按快捷键就在显示器B显示，望修复
2.显示配置1（针对字体/大小/颜色/背景颜色）
3.显示配置2（针对显示方式淡入淡出 或一些过渡动画）
4.建议点击和esc关闭显示 （目前我用AHK实现，体验还可以）
5.失去焦点（显示时点击其它窗口）关闭显示

**Comment by liuzhengdong2** [comment]
> 1.在双显示器未正常运行，始终在一个窗口显示，理想状态是显示器A按快捷键就在显示器A显示，显示器B按快捷键就在显示器B显示，望修复
> 2.显示配置1（针对字体/大小/颜色/背景颜色）
> 3.显示配置2（针对显示方式淡入淡出 或一些过渡动画）
> 4.建议点击和esc关闭显示 （目前我用AHK实现，体验还可以）
> 5.失去焦点（显示时点击其它窗口）关闭显示

@lingchuanbo  都可，但得等到21.1.0版本了，最近没什么空了。

**Comment by BetterWorld-Liuser** [comment]
@lingchuanbo 显示自定义功能已更新, 现在应用不会再占据顶部了
