### ISSUE TITLE
快捷键自定义

### ISSUE THREAD

**Issue by lingchuanbo** [BetterWorld-Liuser/XiaoChao#4]
1.现在alt+s快捷键跟我的一些常用软件有冲突，大神能否提供修改
2.能否提供一个命令行方式 比如 ShortCutHelper.exe /o

**Comment by BetterWorld-Liuser** [comment]
我有点不明白命令行方式是什么意思，是通过命令行查询快捷键吗？比如说ShortCutHelper.exe -tilte Word ？ @lingchuanbo

**Comment by lingchuanbo** [comment]
提供一种 命令行方式 实现目前alt+s 功能

**Comment by BetterWorld-Liuser** [comment]
@lingchuanbo 新版本已支持自定义快捷键
