### ISSUE TITLE
快捷键过长可能会显示不全

### ISSUE THREAD

**Issue by Trrrrw** [BetterWorld-Liuser/XiaoChao#5]
![image](https://user-images.githubusercontent.com/68099555/139789806-e01206be-10ea-4733-a41a-d7da0e2480fe.png)
自己添加的快捷键，太长了显示不出来。

**Comment by BetterWorld-Liuser** [comment]
@Trrrrw 目前还没有自适应宽度，只能写短点

**Comment by BetterWorld-Liuser** [comment]
通过悬浮气泡显示了
