### ISSUE TITLE
问题很严重

### ISSUE THREAD

**Issue by lhj5426** [BetterWorld-Liuser/XiaoChao#7]
![image](https://user-images.githubusercontent.com/30548000/153525806-f6d9231f-aebb-43f6-8d1f-e3f8f35b4f59.png)
小众软件过来的 
我这刚下载 随便写了个功能 我还没全写下呢 就已经 这样了。。。

**Comment by lhj5426** [comment]
顺便要是能自定标背景图片就好了 那么大一块很适合放一张美图壁纸

**Comment by BetterWorld-Liuser** [comment]
> ![image](https://user-images.githubusercontent.com/30548000/153525806-f6d9231f-aebb-43f6-8d1f-e3f8f35b4f59.png) 小众软件过来的 我这刚下载 随便写了个功能 我还没全写下呢 就已经 这样了。。。

能详细描述一下问题吗? 你给的图片我没看懂是什么意思

**Comment by BetterWorld-Liuser** [comment]
> 顺便要是能自定标背景图片就好了 那么大一块很适合放一张美图壁纸

懂了, 目前还不打算支持自适应宽度, 因为巨量的文字会导致整个排版没法看. 所以限制了文字的数量, 可以用简短的语言来描述

**Comment by BetterWorld-Liuser** [comment]
通过悬浮气泡显示了所有文字
