### ISSUE TITLE
双屏幕显示问题

### ISSUE THREAD

**Issue by lingchuanbo** [BetterWorld-Liuser/XiaoChao#8]
1.目前不能自适应双屏幕显示  始终在一个屏幕显示
理想操作 应该是 在对象程序的屏幕居中显示 不管是1屏幕 还是2屏幕 程序在哪个屏幕 就在哪个屏幕显示
2.希望出个免安装绿色版

**Comment by BetterWorld-Liuser** [comment]
了解

**Comment by BetterWorld-Liuser** [comment]
22.1.6版本已经解决了 @lingchuanbo
