### ISSUE TITLE
字体太小了，看不清楚，能调字体吗？

### ISSUE THREAD

**Issue by uulaile** [BetterWorld-Liuser/XiaoChao#9]
![Snipaste_2022-02-28_22-58-18](https://user-images.githubusercontent.com/96331996/156005280-0061bd42-4d17-44f1-aa0a-1717a793f0cc.jpg)

**Comment by BetterWorld-Liuser** [comment]
已增大字体

**Comment by Leiyi548** [comment]
> 已增大字体

能不能自己设定字体大小？
